esphome:
  name: mysensors
  platform: ESP8266
  board: esp12e
  includes:
    - ../ESPHomeMySensorsGatewayShim.h
  libraries:
    - EEPROM
    - SPI
    - MySensors

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker

logger:
  level: debug

ota:

custom_component:
  - lambda: |-
      auto MSGS = new MySensorsGatewayShim();
      return { MSGS };